-- *****************************************************************************
-- This file was automatically generated by dmb editor.
-- All changes made in this file will be lost. DO NOT EDIT!
-- *****************************************************************************

return
{
	-- Paths to resource directories relative to the project root directory
	scenesDirectory = "scenes/",
	localizationDirectory = "l10n/",
	namesDirectory = "names/",
	spritesDirectory = "sprites/",
	fontsDirectory = "fonts/",

	-- List of all available languages
	languages = {"ru", "en", "cn"},
	languageNames = {"&Русский", "&Английский", "&Китайский"},
	defaultLanguage = "ru",
	currentLanguage = "ru"
}
